steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  volumes:
  - name: source-repo
    path: /workspace/source-repo
  dir: /workspace/soure-repo
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "***********************"
      pwd
      ls
  
- id: 'kustomize-build'
  name: 'lyft/kustomizer'
  volumes:
  - name: source-repo
    path: /workspace/source-repo
  dir: /workspace/soure-repo
  args: 
  - '-c'
  - | 
      kustomize build distribution

- id: 'git-push'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git clone https://$$GITOPS_DEPLOY_GH_USERNAME:$$GITOPS_DEPLOY_GH_TOKEN@github.com/mbychkowski/gcp-config-controller-deploy.git
      ls
  secretEnv: ['GITOPS_DEPLOY_GH_TOKEN', 'GITOPS_DEPLOY_GH_USERNAME']

# - id: 'Git clone deploy repo'
#   name: 'alpine/git'
#   entrypoint: 'sh'
#   dir: /workspace
#   args: 
#   - '-c'
#   - | 

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_TOKEN/versions/latest
      env: GITOPS_DEPLOY_GH_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_USERNAME/versions/latest
      env: GITOPS_DEPLOY_GH_USERNAME      
