steps:
- id: 'Branch name'
  name: 'alpine'
  entrypoint: 'sh'
  dir: $REPO_NAME
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "***********************"
      pwd
      mv ../* /workspace/$REPO_NAME/*
      ls

- id: 'Git clone deploy repo'
  name: 'alpine/git'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      ls
      git config --global user.name "Michael Bychkowski"
      git config --global user.email "mbychkowski@google.com"
      git clone https://$$GITOPS_DEPLOY_GH_USERNAME:$$GITOPS_DEPLOY_GH_TOKEN@github.com/mbychkowski/gcp-config-controller-deploy.git
      ls gcp-config-controller-deploy
  secretEnv: ['GITOPS_DEPLOY_GH_TOKEN', 'GITOPS_DEPLOY_GH_USERNAME']

# - id: 'Git clone deploy repo'
#   name: 'alpine/git'
#   entrypoint: 'sh'
#   dir: /workspace
#   args: 
#   - '-c'
#   - | 

# - id: "GitOps blueprint"
#   name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
#   dir: /workspace
#   entrypoint: /bin/bash
#   args:
#     - '-c'
#     - |

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_TOKEN/versions/latest
      env: GITOPS_DEPLOY_GH_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/GITOPS_DEPLOY_GH_USERNAME/versions/latest
      env: GITOPS_DEPLOY_GH_USERNAME      
