# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Config Sync GCP ServiceAccount (GSA)
# This GSA can be used to grant Config Sync additional permissions with IAMPartialPolicy
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sync-krmapihost-config-controller # kpt-set: sync-${cluster-name}
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/gitops/configsync/v0.4.2,kpt-fn-live
    cnrm.cloud.google.com/project-id: kpt-bootstrap-001 # kpt-set: ${project-id}
spec:
  displayName: sync-krmapihost-config-controller # kpt-set: sync-${cluster-name}
---
# Allow Config Sync Kubernetes ServiceAccount (KSA) to use the Config Sync GSA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: sync-krmapihost-config-controller # kpt-set: sync-${cluster-name}
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/gitops/configsync/v0.4.2,kpt-fn-live
    cnrm.cloud.google.com/project-id: kpt-bootstrap-001 # kpt-set: ${project-id}
spec:
  resourceRef:
    name: sync-krmapihost-config-controller # kpt-set: sync-${cluster-name}
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:kpt-bootstrap-001.svc.id.goog[config-management-system/importer] # kpt-set: serviceAccount:${project-id}.svc.id.goog[config-management-system/importer]
